[package]
edition = "2021"
name = "bgrt"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
myacpi.workspace = true
uefi.workspace = true
