[package]
edition = "2021"
name = "acpidump"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
myacpi = {path = "../lib/myacpi"}
uefi = "0.17.0"
